package com.example.cst_338_project_2_su_25.entities;

import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.PrimaryKey;

/**
 * This class represents a title that a user has marked as a favorite.
 * It is stored in a table called "FAVORITES_TABLE" in the database.
 * Each favorite is linked to a specific user using a foreign key (userId).
 * If the user is deleted from the database, all of their favorites will also be deleted automatically.
 */
@Entity(tableName = "FAVORITES_TABLE",
        foreignKeys = @ForeignKey(entity = User.class, //connects foreign key to favorites table
            parentColumns = "userId",
            childColumns = "userId",
            onDelete = ForeignKey.CASCADE //if user is deleted, so are there associated favorites
        )
)

public class Favorites {

    /**
     * The primary key for each favorite entry.
     * Auto-generated by Room to ensure uniqueness.
     */
    @PrimaryKey(autoGenerate = true)
    public int favoritesId;

    /**
     * The ID of the user who marked this title as a favorite.
     * This field serves as a foreign key referencing the User entity.
     */
    public int userId;

}
