package com.example.cst_338_project_2_su_25.entities;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.cst_338_project_2_su_25.database.RevuDatabase;

import java.util.Objects;

/**
 * MediaTitle.java
 *
 * <p>This class is for a media title entity for a movie or TV show.
 *
 * <p> This class is used with the Room database library to store and retrieve
 * media title information such as the title name, type (movie/show), and genre.
 *
 *
 * <p> Each instance of this class corresponds to a row in the RevuDatabase MEDIA_TABLE.
 */
@Entity(tableName = RevuDatabase.MEDIA_TABLE)
public class MediaTitle {

    /**
     * The primary key for the media title entry.
     * Auto-generated by Room to ensure uniqueness.
     */
    @PrimaryKey(autoGenerate = true)
    private int mediaTitleId;
    /**
     * The name of the media title).
     */
    private String title;

    /**
     * The type of media.
     */
    private String type;

    /**
     * The media rating.
     */
    private float rating;

    /**
     * The genre of the media.
     */
    private String genre;

    private int userId; // Foreign key

    /**
     * Constructor for the MediaTitle class with title, type, and genre.
     *
     * @param title the name of the media
     * @param type  the type of media (movie or show)
     * @param genre the genre category of the media
     */
    public MediaTitle(String title, String type, float rating, String genre, int userId) {
        this.title = title;
        this.type = type;
        this.rating = rating;
        this.genre = genre;
        this.userId = userId;
    }

    /**
     * Checks whether some other object is "equal to" this one.
     *
     * <p> Objects are considered equal if their
     * showMovieId, title, type, and genre fields match.
     *
     * @param o the object to compare with
     * @return true if the objects are equal otherwise returns false
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        MediaTitle that = (MediaTitle) o;
        return mediaTitleId == that.mediaTitleId && Objects.equals(title, that.title) && Objects.equals(type, that.type) && Objects.equals(genre, that.genre);
    }

    /**
     * Returns a hash code value for this object.
     *
     * @return a hash code based on the fields showMovieId, title, type, rating, and genre.
     */
    @Override
    public int hashCode() {
        return Objects.hash(mediaTitleId, title, type, rating, genre);
    }

    /**
     * Returns the genre of the media title.
     *
     * @return the genre string
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Sets the genre of the media title.
     *
     * @param genre the new genre string
     */
    public void setGenre(String genre) {
        this.genre = genre;
    }

    /**
     * Returns the unique ID of the media title.
     *
     * @return the auto-generated media ID
     */
    public int getMediaTitleId() {
        return mediaTitleId;
    }

    /**
     * Sets the ID of the media title.
     *
     * @param mediaTitleId new media ID
     */
    public void setMediaTitleId(int mediaTitleId) {
        this.mediaTitleId = mediaTitleId;
    }

    /**
     * Returns the title of the media.
     *
     * @return the media title string
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the title of the media.
     *
     * @param title the new title string
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the type of the media ("Movie" or "TV Show").
     *
     * @return the media type string
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the type of the media.
     *
     * @param type the new media type string
     */
    public void setType(String type) {
        this.type = type;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public float getRating() {
        return rating;
    }

    public void setRating(float rating) {
        this.rating = rating;
    }

    @NonNull
    @Override
    public String toString() {
        return title + '\n' +
                "Rating: " + rating + '\n' +
                "Genre: " + genre + '\n';
    }
}
